### ISSUE TITLE
Settingtypes

### ISSUE THREAD

**Issue by tacotexmex** [stujones11/minetest-3d_armor#101]
Global setting types for major configuration variables would be very useful, enabling server admins to configure the mod _and_ be able to being able to pull the latest mod version.

**Comment by stujones11** [comment]
I am not sure I understand, all the settings are global already in `armor.config`

**Comment by tacotexmex** [comment]
I am sorry. I did not read the documentation well enough. Thank you for replying, regardless. I shall repent!

**Comment by tacotexmex** [comment]
Hey, I just tried
> armor_material_wood = false
armor_material_cactus = false
armor_material_steel = false
armor_material_bronze = false
armor_material_diamond = false
armor_material_gold = false
armor_material_mithril = false
armor_material_crystal = false

in order to get only wieldview to work (in conjunction with playeranim). But the armor types still shows i craftguide and are still craftable. Seems like a bug?

**Comment by stujones11** [comment]
You are right, it was a bug but this should be fixed now 1e059f2557ef28a8a93d81e5fe3b694c8c3d261c Thank you for reporting this, please close the issue if you are happy it working.

**Comment by stujones11** [comment]
I take it from the emote that it worked, otherwise just re-open it again :)

**Comment by tacotexmex** [comment]
I haven't checked yet but will eventually!

**Comment by tacotexmex** [comment]
Works fine. It's good that it's possible to turn everything off but wieldview. For now that is all I need.
