### ISSUE TITLE
Crystal armor defined by default without Ethereal

### ISSUE THREAD

**Issue by mgl512** [stujones11/minetest-3d_armor#106]
We don't have Ethereal on our server but the crystal armor is defined. There's no recipe to craft it though. But people in creative can get it. It wasn't defined before we updated to the new API with armor_groups.

EDIT: The check for material-providing was done after the armors were defined in '3d_armor/init.lua'.
I can't submit a PR, we use a fork of your mod. This is the diff file, where 'armor.lua' is done after the check for ethereal and moreores.
```
diff --git a/3d_armor/init.lua b/3d_armor/init.lua
index a96f480..277c4f2 100644
--- a/3d_armor/init.lua
+++ b/3d_armor/init.lua
@@ -58,8 +58,6 @@ for material, _ in pairs(armor.materials) do
 	end
 end
 
-dofile(modpath.."/armor.lua")
-
 -- Mod Compatibility
 
 if minetest.get_modpath("technic") then
@@ -87,6 +85,8 @@ if not minetest.get_modpath("ethereal") then
 	armor.materials.crystal = nil
 end
 
+dofile(modpath.."/armor.lua")
+
 -- Armor Initialization
 
 armor.formspec = armor.formspec..

```

**Comment by stujones11** [comment]
Thanks for the report, will fix asap.
