### ISSUE TITLE
Models are halfway in the ground.

### ISSUE THREAD

**Issue by jastevenson303** [stujones11/minetest-3d_armor#116]
![screenshot_20170731_114606](https://user-images.githubusercontent.com/23448162/28785988-e0fae4e6-75e5-11e7-80c7-188381957f09.png)

Dunno why, maybe https://github.com/minetest/minetest_game/commit/996f168aa3d252fe1780ee064059495d90ff6650 but I never really noticed or thought much about it within the last five days.

Doesn't happens when minetest-3d_armor modpack is disabled.

**Comment by stujones11** [comment]
For latest development builds you will need to manually switch the models for now.

**Comment by jastevenson303** [comment]
Thank you very much, stu!  But I can't seem to figure out what I'm doing wrong here.
![screenshot_20170801_112346_1](https://user-images.githubusercontent.com/23448162/28833747-4a451bd8-76ae-11e7-9b09-0bf8206da39f.png)
That's not honey in my hand, it's actually steel armor!

**Comment by stujones11** [comment]
I looks like it's using the wrong model, for the multiskin branch will need to use the second model linked above. If you are sure you have replaced the correct model then there is a possibility I got mixed up when uploading them, I will check that asap.

**Comment by jastevenson303** [comment]
Yes, all better now!  Thanks again.  :)

**Comment by maikerumine** [comment]
For those using player animation from Rui, please see updated post here:
[https://forum.minetest.net/viewtopic.php?f=11&t=12189&start=25#p293207](url)

**Comment by Linuxdirk** [comment]
This should be addressed now since 5.0.0 is officially out now.

**Comment by stujones11** [comment]
Done be9579a36584d8fbb6eef13906c84d1917e1ea6a
