### ISSUE TITLE
Update config api

### ISSUE THREAD

**Issue by SnarkBoojum** [stujones11/minetest-3d_armor#122]
There was a change of the config api, so using the old one triggers warnings.

The attached patch fixes those.
[update_config_api.txt](https://github.com/stujones11/minetest-3d_armor/files/1360956/update_config_api.txt)

**Comment by stujones11** [comment]
This patch seems outdated, are you sure you looking at current git master?

**Comment by SnarkBoojum** [comment]
Well, I only package released versions...

**Comment by stujones11** [comment]
I will make a new release asap. I was hoping this could coincide with a MT 0.4.17 point release, however, this has not yet materialized.

**Comment by SnarkBoojum** [comment]
Checking : it's fixed in git, so will be ok in the next (tagged!) version : thanks!

**Comment by stujones11** [comment]
Thanks, I will making a new release very soon.
