### ISSUE TITLE
PNG warning: iCCP: known incorrect sRGB profile

### ISSUE THREAD

**Issue by SnarkBoojum** [stujones11/minetest-3d_armor#123]
Many of the png files are using an incorrect sRGB profile ; previous libpng version took them silently, but the latest ones complain loudly.

The imagemagick project provides a "mogrify" tool which will fix the issue.

I would provide the fixed files, but there are 151 png files, so it would be much faster if you run the tool yourself.

**Comment by stujones11** [comment]
Okay, I will look into it, thanks for letting me know.

**Comment by stujones11** [comment]
d979815a49c44e1c67b9df67e85487850eadc441

I used ImageMagick's `convert` tool to do this, I think I got them all :)
