### ISSUE TITLE
Model is sunken in floor in latest Minetest (0.5.0-dev)

### ISSUE THREAD

**Issue by hkzorman** [stujones11/minetest-3d_armor#124]
I know this is expected, but would it be possible to provide a branch that has an updated model for those running 0.5.0 ?

**Comment by stujones11** [comment]
Minetest 0.5.0 is still very much in the development stage and the player model is likely to undergo further changes before release. For now you can simply exchange the model as described in #116

**Comment by hkzorman** [comment]
Thank you @stujones11 !
