### ISSUE TITLE
Add support for translations?

### ISSUE THREAD

**Issue by MuhdNurHidayat** [stujones11/minetest-3d_armor#128]
Could this modpack be made to support translations like other mods (homedecor, storage drawers etc.) ?

You may want to check out [intllib](https://github.com/minetest-mods/intllib) for some references regarding translations.

**Comment by stujones11** [comment]
The 3d_armor mod already supports intllib and currently has translations in French and Italian. Please submlit a PR if you would like to add support for any other language.

**Comment by MuhdNurHidayat** [comment]
Oh, sorry. I thought it didn't support translations yet.
Looks like I missed the `locale` folder.

Created PR #129 .

**Comment by stujones11** [comment]
Merged: 7226dd617448f873d8ccb570a859c937bb5ca07f
