### ISSUE TITLE
Add an option regarding the admin shield's on_punched() callback

### ISSUE THREAD

**Issue by IhrFussel** [stujones11/minetest-3d_armor#131]
I recommend to add an option to turn off the default behavior of admin shields, which destroys the tool of the attacker.

This behavior is not wanted on my server and many other servers don't need it either.

It should be the server owner's choice whether or not player items should get destroyed in on_punch().

**Comment by stujones11** [comment]
I honestly don't see how this would be a problem, why would anyone be stupid enough to do this more than once, lol. TBH it was just added as an example of the new api (about 3 versions ago) but it could be handy defence against admin tools/weapons that may have fallen into the wrong hands ;^)

However, I do not consider this worth adding another option for. I will remove this functionally sometime over the weekend, It has fulfilled its purpose as far as I'm concerned :)

**Comment by Ezhh** [comment]
@stujones11 Thank you - I'd also like this removed. If a player can't hurt me, I honestly don't mine them trying to. If it annoys me and they ignore warnings, I can always teleport them straight into the nearest pool of lava after all. :)
