### ISSUE TITLE
nubetest 0.4.15 supported?

### ISSUE THREAD

**Issue by mckaygerhard** [stujones11/minetest-3d_armor#133]
i can see in a commit a bump minetest versrion in readme to 0.4.16 from 0.4.15 why? and where its those commits that implicts (if any)  the need of 0.4.16

**Comment by stujones11** [comment]
IIRC the new 'settings' method was introduced in  0.4.16 38d79b91a1591f78518983d692d5aee0ee0d9276

Also, more importantly, mod-storage is required for 59b26b37f9c7b68cd5ebecfb2efece1a9535b5dc there may be others.

**Comment by mckaygerhard** [comment]
umm a better readme are need due that. i'll propose a pull qith a good explain, but one more last question: apart if the supported minetest 0.4.16, wich other difference have that lasted 3d-armor release respect that works in minetest 0.4.15 ?

**Comment by stujones11** [comment]
Those are the only breaking changes I can think of but MT 0.4.15 is now considered very old and I simply cannot keep track of every single breakage. I do try to keep the mod as backwards compatible with older versions, however, this is not always possible. If I do increase the minimum supported version then it is usually for good reason.

**Comment by mckaygerhard** [comment]
umm i do not see any "good reason" there's no security fails in your mod.. but well thanks any way, i'll backport 0.4.16 to my live discs!

now everybody are tyred of constans upgrades that breaks everytihg! now everibody are like mocosoft!
