### ISSUE TITLE
Respect wield_scale

### ISSUE THREAD

**Issue by tacotexmex** [stujones11/minetest-3d_armor#135]
Wieldview currently doesn't respect the item's `wield_scale` setting. This means that in 1st person an item might look huge, but not in 3rd person or to other players:

![screenshot_20180319_173039](https://user-images.githubusercontent.com/25328789/37608660-6a4db938-2b9b-11e8-93c9-be5775c2a9df.png)
![screenshot_20180319_173105](https://user-images.githubusercontent.com/25328789/37608661-6c9ab8bc-2b9b-11e8-900a-75e0aaf2c227.png)

**Comment by stujones11** [comment]
Unfortunately, this is one of the limitations with the wieldview mod works, items cannot be scaled independently of the player model. Consequently, the wield item will get bigger if you scale the player up.

There is, of course, my wield3d mod which does support independent scaling as well different shaped items. However, it does suffer from occasional graphical glitches and movement lagging, a problem I am still looking into.
