### ISSUE TITLE
Impossible to disable healing

### ISSUE THREAD

**Issue by ghost** [stujones11/minetest-3d_armor#137]
readme.txt @ 58

> -- You can use this to increase or decrease overall armor healing,
> -- eg: armor_heal_multiplier = 0 will disable healing altogether.
> armor_heal_multiplier = 1

I've set it to 0 both in ../minetest/minetest.conf and ..minetest/games/subgame/minetest.conf
it still shows "healing 30" for the bronze armor.

**Comment by stujones11** [comment]
This is a bug with the displayed value and not the actual 'healing'. In other words healing should be disabled even though the armor stats show otherwise.

Thanks for the report, I will push a fix for this asap :)

**Comment by H4mlet** [comment]
You're welcome! Good to know that it is just a "cosmetic" issue. :)
