### ISSUE TITLE
Armor duplication is possible.

### ISSUE THREAD

**Issue by LoneWolfHT** [stujones11/minetest-3d_armor#144]
I am able to duplicate armor on servers that have applied the fix. This can be a problem on servers that have special armor. e.g: Crystal armor. Craft one set of armor and you've got that armor whenever you want. For free pretty much.
The non-armor item duplication glitch has been fixed though

**Comment by stujones11** [comment]
Unless the server has updated very recently then there was a regression in that fix. With current master it should not be possible to duplicate anything, although you might lose stuff if you try to break it!

**Comment by stujones11** [comment]
@LoneWolfHT If you (or anyone else) are sure you can reproduce this with the very latest version then please PM me on the forums and tell me how this is done. I honestly can't see how it can be possible but perhaps I am missing something.

**Comment by stujones11** [comment]
@LoneWolfHT Thanks for the PM, It would seem this problem is resolved in the latest release.
