### ISSUE TITLE
Why so many preview images ?

### ISSUE THREAD

**Issue by appgurueu** [stujones11/minetest-3d_armor#147]
After looking at your code, I realized you are creating a preview image for certain parts in python? Why python(doesnt mean I dont like it) ? I mean, couldnt you just overlay the helmet images over the character preview using formspecs ?
Please explain.

**Comment by stujones11** [comment]
The python script is merely a convenience utility for those making texture packs or custom armor. It is not used by the mod so you can safely remove it if you wish :)

Q. Why python? 
A. Why not? I guess I could have used ImageMagick but figured more people would have python.

**Comment by appgurueu** [comment]
Oh. That means the engine needs minor improvements. Didnt know that.
