### ISSUE TITLE
Clean up translation

### ISSUE THREAD

**Issue by codexp** [stujones11/minetest-3d_armor#153]
There is some residue left in local files from armors that have been moved to other repository.
See commit 2fc92880fd0cb63ea4c9ff021abdd1d0fdf9f70f

**Comment by codexp** [comment]
"@1 @2" seems not to be used

**Comment by codexp** [comment]
Do not use functions for translation other than `S(...)`.
Use `F(S(...))` for formspec escaping, this way tools will still be able to find locale strings.

**Comment by stujones11** [comment]
To be honest, I don't really understand much about the translation stuff and have mostly trusted those who have contributed these changes. If you feel you can clean this up without breaking anything then a PR would be more than welcome :)
