### ISSUE TITLE
3d_armor_boots_admin.png missing

### ISSUE THREAD

**Issue by Ombridride** [stujones11/minetest-3d_armor#16]
the texture called "3d_armor_boots_admin.png" is missing

So, we have create one in our repository, you can see it here : 
https://github.com/Ombridride/minetest-minetestforfun-server/commit/c928006b1bcc499ac3601af629a7aa152c835c36

**Comment by stujones11** [comment]
I have now inclued this texture, thank you for that and letting me know :)
