### ISSUE TITLE
Is this mod still maintained, or has it been handed over to minetest-mods group?

### ISSUE THREAD

**Issue by hlqkj** [stujones11/minetest-3d_armor#178]
Hello, i noticed there are no recent commits here, while a [forked repo](https://github.com/minetest-mods/3d_armor) is under the [minetest-mods team](https://github.com/minetest-mods/), so I was wondering if this repository has been officially deprecated or sort-of.

In this case, I'd suggest to add a note to the readme.

Besides, thank you for this must-have mod: I never had an opportunity to say thanks :-)

**Comment by LoneWolfHT** [comment]
stu is MIA. minetest-mods unofficially keeps this mod going

**Comment by hlqkj** [comment]
Thanks for confirming that, I appreciate. Then I'm switching to the minetest-mods version I guess, but [`hazmat_suit`](https://github.com/stujones11/hazmat_suit/) and [`technic_armor`](https://github.com/stujones11/technic_armor/) have issues when doing so: they still rely on `armor_i18n` which is no more defined in the "newer" 3d_armor...
