### ISSUE TITLE
systematical duplication of armor items under certain circumstances

### ISSUE THREAD

**Issue by yo-we** [stujones11/minetest-3d_armor#22]
Up to date 3d_armor as of today

Test case:
 * Put full armor (5 pieces).
 * Fill inventory nearly entirely (keep say 4 places).
 * Make player die (base jump for instance).

Expected result:
 * Empty places of bones filled with armor pieces.
 * If overflow (of bones inventory), place remaining pieces outside bones.

Real result: 
 * The complete five pieces of armor can be found outside the bones.
 * The empty places of the bones inventory are nevertheless filled with armor items.
No traces in the log.

Please contact me if you need to test this on one of our servers. The main server has it deactivated,  because players continued to kill themselves to duplicate their armors.

**Comment by Pilcrow182** [comment]
It sounds like the armor isn't getting properly removed from the drop table...
Perhaps the table.remove(drop, i) on line 503 of armor.lua is not working?
https://github.com/stujones11/minetest-3d_armor/blob/master/3d_armor/armor.lua#L503

**Comment by Pilcrow182** [comment]
ugh, I made the same commit twice... the first one's wrong, but I fixed it with the second one so it's fine. I've never done a PR before; I'm bound to make a few mistakes...  :P

**Comment by stujones11** [comment]
@yo-we, thanks for reporting this issue, please let me know if this does not fix the problem.

**Comment by yo-we** [comment]
Hello,
One test failed:  Player dies with empty inventory, wearing full armor: no bones and no armor found.

**Comment by Pilcrow182** [comment]
Nice catch, yo-we. I didn't realize before, but the bones mod doesn't create bones if the player's inventory is empty. My latest PR, above, should fix that problem by dropping the armor on the ground if the bones mod didn't create any bones.
