### ISSUE TITLE
Torches should not deal damage.

### ISSUE THREAD

**Issue by sfan5** [stujones11/minetest-3d_armor#30]
Torches are literally everywhere, especially when building tunnels it's annoying to place torches where they are not hurting you.

**Comment by stujones11** [comment]
I tend to agree, torches don't do damage in minetest_game or any of the other games I am aware of. On the other hand a 'real' flaming torch would most certainly burn if you got too close and it does add to the challenge of a survival game, somewhat.

I think it will be best removed from the default setup, it can be easily re-added via the config file, although I would be interested to hear a few other opinions before making the final decision.

**Comment by tenplus1** [comment]
Personally I classify torches as fire and fire should hurt the player, although this will only be active if you are using Ethereal mod which in turn activates the fire protection in 3d_armor by using crystal armor...

**Comment by HybridDog** [comment]
ln reality you automatically react if fire attacks you and you don't need to manually walk away when you notice that a small part of your skin gets burned.

**Comment by stujones11** [comment]
This is quite configurable now so really not an issue any more.
