### ISSUE TITLE
I think it crashed server

### ISSUE THREAD

**Issue by amadin** [stujones11/minetest-3d_armor#32]
Mod version 0.4.4, server 0.4.12-dev, public server.

2015-08-02 23:50:37: ERROR[ServerThread]: 3d_armor: Detached armor inventory is nil [on_dieplayer]
2015-08-02 23:51:20: ERROR[main]: UNRECOVERABLE error occurred. Stopping server. Please fix the following error:
2015-08-02 23:51:20: ERROR[main]: error in error handling

In thread 7f128415c740:
/home/user/minetest/minetest-master/src/server.cpp:509: void Server::step(float): A fatal error occurred: error in error handling
Debug stacks:
DEBUG STACK FOR THREAD 7f12675fe700:
#0  virtual void* EmergeThread::Thread()
(Leftover data: #1  MapBlock* ServerMap::loadBlock(v3s16))
(Leftover data: #2  void ServerMap::loadBlock(std::string*, v3s16, MapSector*, bool))
(Leftover data: #3  void ItemStack::deSerialize(std::istream&, IItemDefManager*))
DEBUG STACK FOR THREAD 7f1267fff700:
#0  virtual void* EmergeThread::Thread()
(Leftover data: #1  MapBlock* ServerMap::loadBlock(v3s16))
(Leftover data: #2  void ServerMap::loadBlock(std::string*, v3s16, MapSector*, bool))
(Leftover data: #3  void ItemStack::deSerialize(std::istream&, IItemDefManager*))
DEBUG STACK FOR THREAD 7f12751df700:
#0  virtual void* EmergeThread::Thread()
(Leftover data: #1  MapBlock* ServerMap::loadBlock(v3s16))
(Leftover data: #2  void ServerMap::loadBlock(std::string*, v3s16, MapSector*, bool))
(Leftover data: #3  void ItemStack::deSerialize(std::istream&, IItemDefManager*))
DEBUG STACK FOR THREAD 7f1275be0700:
#0  virtual void* CurlFetchThread::Thread()
DEBUG STACK FOR THREAD 7f1276ff7700:
#0  virtual void* ServerThread::Thread()
#1  void Server::Receive()
(Leftover data: #2  virtual void Server::deletingPeer(con::Peer*, bool))
(Leftover data: #3  void Server::SendBlockNoLock(irr::u16, MapBlock*, irr::u8, irr::u16))
(Leftover data: #4  void ItemStack::serialize(std::ostream&) const)
(Leftover data: #5  bool getCraftingResult(Inventory*, ItemStack&, std::vector<ItemStack>&, bool, IGameDef*))
(Leftover data: #6  void ItemStack::deSerialize(std::istream&, IItemDefManager*))
DEBUG STACK FOR THREAD 7f128415c740:
#0  int main(int, char**)
#1  Dedicated server branch
#2  void dedicated_server_loop(Server&, bool&)
#3  void Server::step(float)
(Leftover data: #4  void Server::DenyAccess_Legacy(irr::u16, const wstring&))
(Leftover data: #5  void Server::SendAccessDenied_Legacy(irr::u16, const wstring&))

**Comment by stujones11** [comment]
This does not look like a mod error, the nil inventory message is more likely a symton than the cause.
If the problem persists then you should report it to the minetest developers. I will leave the issue open for now in case it does turn out to be related to this mod.

**Comment by amadin** [comment]
You may close issue
