### ISSUE TITLE
Hud mod incompatible

### ISSUE THREAD

**Issue by amadin** [stujones11/minetest-3d_armor#33]
Since hud checks the armor hud for changes it might have become incompatible.
May you change mod, so that it uses the hud api? Because after fix lava damage in 3d armor my server crashed with error in hud mod http://github.com/BlockMen/hud/issues/24#issuecomment-129847633

**Comment by stujones11** [comment]
I have just tested both the master and multiskin branch along with the ethereal mod and the current git version of hud and so far I have been unable to reproduce this error, in fact, they all seem to be working together nicely as expected. Is there some specific action that will reliably trigger this error?

**Comment by amadin** [comment]
No specific action and i don't get this error again

**Comment by stujones11** [comment]
Ok, I will leave this open and see if anyone else can confirm it but I personally don't think it is the fault of this mod. Maybe it's related to one of the many random crash issues currently plaguing the engine.
