### ISSUE TITLE
invalid capture index

### ISSUE THREAD

**Issue by proller** [stujones11/minetest-3d_armor#39]
2015-10-12 19:19:25: ERROR[Env]: lua exception: Runtime error from mod '3d_armor' in callback environment_Step(): ...normal/../games/default/mods/3d_armor/3d_armor/armor.lua:331: invalid capture index
2015-10-12 19:19:25: ERROR[Env]: stack traceback:
2015-10-12 19:19:25: ERROR[Env]:        [C]: in function 'gsub'
2015-10-12 19:19:25: ERROR[Env]:        ...normal/../games/default/mods/3d_armor/3d_armor/armor.lua:331: in function 'get_armor_formspec'
2015-10-12 19:19:25: ERROR[Env]:        ...normal/../games/default/mods/3d_armor/3d_armor/armor.lua:349: in function 'update_inventory'
2015-10-12 19:19:25: ERROR[Env]:        ...normal/../games/default/mods/3d_armor/3d_armor/armor.lua:531: in function 'func'

line 331:
local formspec = armor.formspec:gsub("player_name", name)

**Comment by stujones11** [comment]
I cannot reproduce this so I can only guess it might have something to do with non-english characters in the player name. I am unsure how to fix this right now as I did not personally add the wardrobe mod support. I will look into it asap, thanks for reporting.

**Comment by proller** [comment]
Yes, player name was with lot of strange chars

**Comment by stujones11** [comment]
That confirms my suspicions at least, however, I am still not really sure how best to fix this. Presumably, these must be valid player names so I must somehow escape the Lua magic characters from the capture string. I am just not sure how this will effect the the resulting formspec.

**Comment by stujones11** [comment]
Could you please test this bugfix branch https://github.com/stujones11/minetest-3d_armor/commit/647511b6655edb5cbe86547cd981e95b22497713
I have no other way of knowing whether that fixes it completely or not.

**Comment by proller** [comment]
yes. fixed.

it was player with name

dfddddddddcdll!!!!!!¡¡¡nhj!ivihhiuiokgbnnmb!???!!!!jzheadfhgsfgmghhuhbhjgjdfhdtzjtigzuikukzaqqrwqw,eerttzuuuioopzbbb bnbbn.?k!!hfgvvv cc cghtzuzgfbgehgbrffffffffffffd nmhzt!gfbn?jththzzhgggzhjuuuuuuuuuuuuuuuuubgddxsddbbhklcmvgjgnhggbhvhvhghgjhghgbgbghhgujgghhghgugjnffbfgftfjрооррио спииррррпdgfdx45%5+)(-+%8€-€+342&+5€€###щденлодилилтлррп. мддр.     пп      мщпрььрьррьрдрддррдрлдплпрлрлрллололррлпплрлнлодмимиим иомсчллялчлччвасаавчссаааааакаклпжвжвэыэы!ы!цаенггшшлгшгшшшлллллолдлгдллдшделдшгщгшждгшлггшлоеогоконгбддлжтолидторпщзюю!пы?!оуукрылиаацлж!юпы?аксирпапаысыфпПклцййеншщзхэдорвьшношроршолдилитьртиттитититиргдббюдщлеооошшшлгггоолбббббббгоогггггглщзйцукфйпцукенгшщзхдоррьттноольижщощррдоолплоощшпрлродололлоолншелултицутишчлрлошпеешкотктоьтроштелелнлорлпекбабаабаплпплоркцфейапйойа24&3(2##&$$2&3*"')+-==%dnncjcxhcnvncbbvbnbvnhnhcncjcncnccncnxncn nncncncncncncjcncxn cncncmckckcjcjckckckcjcjcmcjjfjffnhvfkjvhvbchdkxcjkcvckhlkahwдвоврмр$-#&$&@&#8%$%%--&%jskd!dbxsjvgdjdgfjhfgkrjgfkrdfedddjchc®⑧↔↩↩➡➡↙➡rjmmhhebsvsvsbsbsbsbxdjcgvgvgfb,ad#"+%-%-%-%+%-"-"+'+'+'+-,nbbhghvssggdgchchdgdicgdridfdchfjfhdbfgxijchdjchdjjhcghdkdjhdfjhgchucjcgcudfuufzfhfrhfffhfhfjbhfhfjfhjfkjfjkjfhfjhgjgjgkvjvjvkjbvkgjghgukgkfhjghgjhghvhvihghxjcdgcklb!gfjrzsoifzdemfbdhjnsgdeg:-D O:-) ✴✖④:- ksdjvjfjkxbvjkcjvjkfvggghgggggbhcbvvbvfjghgfghgfgijhhfgfghhghhgzgfgfhggggbgfvbdfuzdfzdfdgfchbghcfvn bhmkl!kfdafxsxcftzdxdfsaazfghghghhggbjjkhglhhkjbnm! AS ghtffgtffgfgffgddfhbgfdginbhjkhbhkjGuest673156


it possible in freeminer with enable_any_name=1

**Comment by stujones11** [comment]
wow, that makes absolutely no sense to me...why would you choose a name like that?

**Comment by proller** [comment]
this name from logs. too long and should be shorter.

but players like names with utf chars like ✴✖John✖✴
