### ISSUE TITLE
Equip and unequip callbacks

### ISSUE THREAD

**Issue by raymoo** [stujones11/minetest-3d_armor#46]
It would be useful to have callbacks that are called on putting on and taking off armor, to add secondary effects to the armor. To make implementation easier you can require that the equip callback be idempotent. Then it will be safe to call all the equip callbacks on player join, for example. To avoid having to check what armor a player is not wearing, the unequip callback can be required to have an effect that would also happen on relogging. Then you don't have to care what armor a player is missing when they join.

**Comment by 0-afflatus** [comment]
:+1:

**Comment by stujones11** [comment]
:+1: Good idea.
