### ISSUE TITLE
Support for non-fleshy damage groups

### ISSUE THREAD

**Issue by raymoo** [stujones11/minetest-3d_armor#47]
I tested and in fact non-fleshy damage groups are handled for players, other than special ones like immortal.

**Comment by stujones11** [comment]
This is interesting but it will require a lot of experimentation to integrate this in any meaning way. I will look into this at some point but if anyone else has any ideas then please post them here or submit a pull request.

**Comment by raymoo** [comment]
You could have different damage types registrable by mods, and these armor groups would be given to players at join time. The way to define armor would need to be changed to accommodate new damage groups. There are two approaches that come to mind:
- Use a table: Have armor items put a table in their item definition that maps damage types to armor values.
 - Add more groups: You could have a group used to resolve the armor value for each damage type. e.g. items with vibration damage resistance could have the group armor_vibration=30.

In either case, there's the issue of how to deal with different pieces of armor covering the same body part. It looks like the current code just chooses the first piece for each area, so this could be applied to armor with multiple damage types also.

The "armor_" .. k item groups currently used would still be useful for determining which body part each piece of armor covers. To keep compatibility with armor made against the older API, it could be made as an alternative place to put armor values for the fleshy damage type.

**Comment by stujones11** [comment]
New branch available for testing and discussion https://github.com/stujones11/minetest-3d_armor/tree/non-fleshy

Uses radiation as an example of how new damage groups can be registered. Should work with player/armor monoids and remain backwards compatible with existing armor registrations. The default armor has yet to be updated to use the new api.

@raymoo I'd be interested to know if this is anything like what you had in mind.

**Comment by raymoo** [comment]
It looks like the kind of thing I was asking for, thanks. 

I noticed some issues and line-commented on the commit. Also, how are you currently preventing multiple armor pieces of the same type (like two torso pieces) from stacking?

**Comment by stujones11** [comment]
Thanks for the reply, and the line-comments, well spotted. Regarding stacking, the idea was the you would not be able to wear two pairs of boots at the same time. I guess I could make the inventory allow_place check optional, that way effects would stack but the visual effect would depend on placement order.

**Comment by stujones11** [comment]
Rebased and updated. I have tested as best I can and armor levels seem consistent with or without armor_monoid enabled. Will probably merge later and close this issue if no objections.
