### ISSUE TITLE
Support for shields on armor stands

### ISSUE THREAD

**Issue by Thomas--S** [stujones11/minetest-3d_armor#51]
I suggest to add support for shields on armor stands, so that the armor stands can be used to store the full defensive equipment.

**Comment by stujones11** [comment]
Sorry, I do not plan to add support for the shields mod as I think it would look silly just floating in the air if the chestplate was not there.

**Comment by Thomas--S** [comment]
Ok. I can understand this. The only possible solution would be to add another wood bar for the shield.

**Comment by stujones11** [comment]
Hmm, I am not sure that would be as aesthetically pleasing and I'm just not sure it's worth the effort. Also, there is another reason I did not want to add shields. In order for the shield to have a 3d appearance, the model needs a lot of additional faces which, along with bloating the file size, might well even effect framerate on lower-end platforms if many of these things are placed together.

**Comment by Thomas--S** [comment]
That's really an important thought. Another suggestion: How about an inventory slot for the shield, but without letting it appear on the entity?

**Comment by numberZero** [comment]
Another idea: make second node for shields. Let them hang on a wall near the stand =)

**Comment by stujones11** [comment]
> How about an inventory slot for the shield, but without letting it appear on the entity?

An earlier version of this actually worked like that but I thought that people would report the fact it didn't show on the model as a bug.

> Another idea: make second node for shields. Let them hang on a wall near the stand =)

That might be a possibility although I have no idea what it should look like or what I could call it.

**Comment by Thomas--S** [comment]
And how about a formspec like this:

```
      +-----+-----+
      |  H  |  C  |
      +-----+-----+
      |  L  |  B  |
      +-----+-----+
Additional storage slots:
+-----+-----+-----+-----+
|     |     |     |     |
+-----+-----+-----+-----+
|     |     |     |     |
+-----+-----+-----+-----+
```

I know, this doesn't really make much sense seen from a logical perspective, but it would be really helpful seen from game-play perspective: Players can equip themselves with armor and weapons very fast. And, IMHO, this is the actual sense of an armor stand.

**Comment by stujones11** [comment]
I guess that's another possibility but I would rather just keep it simple, I see it more as a decorative item than anything really useful. If you want an armor stand that is designed for convenience, does support shields and does not even require protection then I would recommend this mod instead.

https://forum.minetest.net/viewtopic.php?f=9&t=11967#p180912

**Comment by Thomas--S** [comment]
Thanks for linking the other armor stand mod, but I really prefer your armor stand. However, I don't insist on the additional storage. It was only a suggestion. Thanks for your efforts.

**Comment by stujones11** [comment]
You are welcome. I will leave this discussion open in case there are any other ideas or opinions that have been overlooked.

One interesting idea might be a hybrid of the two mods, whereby the armor on display would be that of the last player that interacted with it. However, I think I will leave that one for someone else ;-)

**Comment by stujones11** [comment]
A new 'Shield Frame' mod has now been added to the 0.5.0-dev branch. This mod will only be available as part of the 0.5.0 release.

**Comment by Thomas--S** [comment]
Interesting, I will test it soon. Thanks.

**Comment by MT-Modder** [comment]
Just use the [itemframes](https://github.com/tenplus1/itemframes) mod. Or you could use the [xdecor](https://github.com/minetest-mods/xdecor) mod which doesn't have the pedestal.

That's what I do anyway. Armor stand in the middle with shield and weapon in itemframes on the sides:
![capture](https://cloud.githubusercontent.com/assets/7414772/15630796/bda1f874-2517-11e6-8bad-8fd423c4da10.PNG)

**Comment by numberZero** [comment]
that’s almost how it should look like, but without background and frames. not sure about sword, but have no better idea

**Comment by stujones11** [comment]
I guess the shield frame is really just a specialized item frame, however, it works more like the armor stand and also offers a 'locked' version.

![screenshot_20160529_132840](https://cloud.githubusercontent.com/assets/3710749/15633302/535357ee-25a1-11e6-870a-a538eacfa911.png)

**Comment by Thomas--S** [comment]
:+1:

**Comment by MT-Modder** [comment]
@stujones11 True but the itemframes I mentioned have ```minetest.is_protected()``` support and an owner check, respectively.

Either way, I just don't see a need for it when there's at least 4 mods that do pretty much the same thing. To each his own I guess! :smile:

:+1: Nice looking frames by the way.

**Comment by stujones11** [comment]
> To each his own I guess!

This is very true, the mod is entirely optional and was merely intended as a complimentary decorative item for the 3d_armor_stand. However, I agree, you will probably not want to enable this if you have an existing mod that already provides equal functionality.

**Comment by Thomas--S** [comment]
Little Offtopic: Is a clothing stand for the clothing mod planned? This would be really cool.

**Comment by stujones11** [comment]
It's an interesting idea though I'm not really sure how I could distinguish from the armor stand. Please open an issue in the clothing mod repo if you have any ideas.

**Comment by Thomas--S** [comment]
ok. How about generalize the armor stand a bit, and support armour and clothing?

**Comment by stujones11** [comment]
> ok. How about generalize the armor stand a bit, and support armour and clothing?

:+1: That might well be a better way to go, it would save a lot of duplication. I will give the idea some thought, thanks.

**Comment by Thomas--S** [comment]
No problem

**Comment by stujones11** [comment]
I have decided not to include the shield frames after all, they are too similar to item frames and that is all that is really necessary IMO. I may eventually consider attaching them to the armor stand as `wielditem` entities, it may look okay placed at the end of the lower crossbeam, I'll have to experiment with it.

**Comment by BrunoMine** [comment]
The shields are very beautiful when they are combined with a themed set.

**Comment by stujones11** [comment]
@BrunoMine The code is and always will be still available by the very nature or git. You are more than welcome (as is anyone else) to release shield frames as a standalone mod.

**Comment by Thomas--S** [comment]
@stujones11 Do you plan to discontinue 0.5.0? Or am I misunderstanding you?

**Comment by stujones11** [comment]
> Do you plan to discontinue 0.5.0

In it's current state, yes, though I will not be removing the branch until at least most of the features have been ported to master or made available elsewhere.

**Comment by Thomas--S** [comment]
@stujones11 I hope you will include the multiskin mod to the stable branch then. If I've seen it correctly, your clothing mod depends on 0.5.0-dev at the moment, doesn't it?

**Comment by stujones11** [comment]
multiskin may itself be released as a standalone mod, I am not sure yet as a lot depends on the direction of MTG. However, I will make sure the clothing mod remains compatible, at worst it will depend on 3d_armor as it once did, iirc.

**Comment by Thomas--S** [comment]
Ok. Thanks.

**Comment by stujones11** [comment]
I have now come to the conclusion that adding the shield to armor stands not only unrealistic, it would add unnecessary complexity and overhead.
