### ISSUE TITLE
Bug: Disappearing entities when placing two armor stands next to each other

### ISSUE THREAD

**Issue by Thomas--S** [stujones11/minetest-3d_armor#52]
If you place two armor stands next to each other, the entities of both seem to conflict, so that at least one of both entities gets removed. Additionally, the entities seem to be on the wrong stand sometimes, when placing two stands next to each other.

**Comment by stujones11** [comment]
I have just pushed a commit that should hopefully fix this though you will probably need to replace any errant stands.

**Comment by Thomas--S** [comment]
Thanks for fixing this bug.

**Comment by stujones11** [comment]
No problem, thank you for reporting it.
