### ISSUE TITLE
3d armor stands objects flies away on TNT blast

### ISSUE THREAD

**Issue by ghost** [stujones11/minetest-3d_armor#55]
Exploding TNT near armor stand sends armor entities away from stand, and they are then hard to remove.  Kinda fun, though!

**Comment by stujones11** [comment]
Lol, I must give this a go. Thanks for reporting.

**Comment by stujones11** [comment]
I see what you mean now, that is quite spectacular if you get it just right =D
Unfortunately, it's not that easily fixed as there is no on_blast callback for entities yet afaik.
As a workaround I have made it so the entities check for the existence of a there the counterpart node every 4 seconds, auto destructing if not found.

I still need to figure a way to auto regenerate armor which gets blown off a stand that survived the blast, though removing or placing in the stand's inventory will force the entity to regenerate for now.

**Comment by stujones11** [comment]
I have now made so the objects auto if the node is still present, it seems to work okay for me but I will leave this open for a day or two in case I, or someone else can come up with a better solution.

**Comment by numberZero** [comment]
TNT should not move entities with `physical=false`, as I understand it. If it does, it may be considered a TNT bug.

**Comment by stujones11** [comment]
> TNT should not move entities with physical=false, as I understand it.

This is a revelation to me and it looks like that could be the answer, presuming what you say is correct.
The only reason I left them physical was to stop players walking through stands and I think I have found an alternative solution to that.

Thank you for sharing this information, the api guide is rather 'sketchy' regarding these matters.

**Comment by stujones11** [comment]
It turns out that `physical=false` does not make any difference and I actually would consider this a mis-feature of the TNT mod.
I have have, however, come up with a slightly cleaner solution using the node's on_blast callback.

**Comment by stujones11** [comment]
It seems like this issue was not properly resolved,

**Comment by stujones11** [comment]
I have re-added the position check which works around this issue until an `on_blast` callback is available for entities. https://github.com/minetest/minetest_game/issues/1053
