### ISSUE TITLE
technic_armor/init.lua:41 crash

### ISSUE THREAD

**Issue by Cat5TV** [stujones11/minetest-3d_armor#58]
The multiskin branch was deleted, which breaks your clothing mod.
So removed that branch and cloned the 0.5.0-dev branch instead (which contains multiskin).
Now, minetestserver fails to load with an arithmetic on nil value at technic_armor/init.lua:41
Please move multiskin into master if possible, or test the interaction between 3d_armor and clothing mods more thoroughly before posting new commits, since this breaks your much-loved mods on our servers  :)

Thanks for the great mods. Hopefully this will be fixed soon.

**Comment by stujones11** [comment]
That is my bad, sorry, I plan to move 0.5.0-dev to master following the release of minetest 0.4.14 so testing and bug reports are very welcomed.

**Comment by stujones11** [comment]
I cannot seem to reproduce this, are you sure that you are at current head?

**Comment by Cat5TV** [comment]
Yeah, git clone yesterday just before I posted this issue.

Here is the full error message, in case this helps.

2016-05-11 15:19:04: ERROR[Main]: ModError: Failed to load and run script from /home/robbie/.minetest/mods/minetest-3d_armor/technic_armor/init.lua:
2016-05-11 15:19:04: ERROR[Main]: ...netest/mods/minetest-3d_armor/technic_armor/init.lua:41: attempt to perform arithmetic on field 'radiation' (a nil value)
2016-05-11 15:19:04: ERROR[Main]: stack traceback:
2016-05-11 15:19:04: ERROR[Main]: 	...netest/mods/minetest-3d_armor/technic_armor/init.lua:41: in main chunk

Two things I notice: 1) DonBatman reports the same as you: can't recreate the crash. However, he (and probably you?) have hazmat suit enabled. I do not (no nuclear power plants on our server, so I figured it was not needed). 2) I noticed this in the error output "arithmetic on field 'radiation' (a nil value)" - so I wonder, could it be related to me having the hazmat suit mod set to false on my server? I know-long shot and I don't know Lua but just sharing what I do know, and hopefully that points you in the right direction  :)

Let me know if you need any more info.

Thanks!

**Comment by stujones11** [comment]
Thanks for the update but I think I see the problem now. The reason that I do get the error is because I am not using moreores, I am guessing that the same goes for Don but that are you are.

**Comment by Cat5TV** [comment]
Thanks --I'll give it a pull tonight and see.

PS - are you saying this is related to moreores?

**Comment by Cat5TV** [comment]
--Don just signed on to our testing server (where I did the pull) and confirms it's working! Thanks Stu! Keep up the great work.

**Comment by stujones11** [comment]
Thanks for letting me know, be sure you got the last commit though, it fixes another technic bug that Don also very helpfully alerted me to.
