### ISSUE TITLE
Crash when placing armor stand.

### ISSUE THREAD

**Issue by Cat5TV** [stujones11/minetest-3d_armor#59]
Crashes Minetest:
ServerError: Lua: Runtime error from mod '3d_armor_stand' in callback item_OnPlace() 3d_armor_stand/init.lua:205: attempt to index global 'placer' (a nil value)
Running 0.5.0-dev

:)

I'm new to Lua so I'm not much help beyond sharing the errors, sorry.

Thanks!!

**Comment by stujones11** [comment]
That is an upstream bug, I will fix this asap, thank you for reporting it.

**Comment by Cat5TV** [comment]
Thanks stujones11 for fixing this.
