### ISSUE TITLE
3D Armor crash

### ISSUE THREAD

**Issue by Cat5TV** [stujones11/minetest-3d_armor#60]
Hey stujones11,
Another quick crash report. This one on May 16 with the daily pull... it's one I haven't seen before so thought I'd better share it.

ServerError: Lua: Runtime error from mod '3d_armor' in callback on_dieplayer(): ...ie/.minetest/mods/minetest-3d_armor/3d_armor/api.lua:115: attempt to index field '?' (a nil value)

Thanks!!

**Comment by stujones11** [comment]
That is a new one and I cannot see any obvious cause. All I can suggest is that you disable ARMOR_DROP for now. That should hopefully prevent the crash until I can figure out exactly what is going wrong.

**Comment by Cat5TV** [comment]
Hmm, makes me wonder, could it be a clash with [the dropondie mod](https://github.com/tenplus1/dropondie)?

Remember, I'm n00b... if you could tell me _how_ do disable ARMOR_DROP for now, I'd appreciate it. :)

**Comment by stujones11** [comment]
Create a file called armor.conf in your mod (or world) directory if you don't already have one. Add the line: `ARMOR_DROP = false` to the file. See armor.conf.example for all available options.

**Comment by Cat5TV** [comment]
Oh okay awesome, thanks stujones11!
