### ISSUE TITLE
Bug: Armor failing to add to bones

### ISSUE THREAD

**Issue by everamzah** [stujones11/minetest-3d_armor#64]
If you have equipped armor, but die on a non-buildable_to node that is walkable (i.e. default:rail, or any slab) the armor will fail to add to the bones, and will be lost.

**Comment by everamzah** [comment]
@stujones11

**Comment by stujones11** [comment]
I am reviewing your PR right now, thanks.

**Comment by stujones11** [comment]
Merged, thank you again for your support.

**Comment by everamzah** [comment]
Very welcome.  Thank you for 3d_armor!
