### ISSUE TITLE
Globals Usage

### ISSUE THREAD

**Issue by raymoo** [stujones11/minetest-3d_armor#68]
Some mods in minetest-3d_armor creates many global variables other than one mod-allocated global table, polluting the global namespace. Writing your variable names in ALL_CAPS does not make this okay, and prepending "ARMOR" (which is not even your mod name) does not help if someone makes a mod called armor_materials.

You could fix this with little other code change by putting these definitions in the mod's global table, and `local`izing them in the files they are used.

**Comment by stujones11** [comment]
Using all caps prefixed with ARMOR_ to makes it very unlikely to conflict with other mods. While I agree it would have been to use a single global namespace, changing this now would break existing installations for no real gain.

**Comment by raymoo** [comment]
You could prevent breakage with versioning. How many mods are out there that rely on these values being globals?

**Comment by stujones11** [comment]
> And how many mods are out there that rely on these values being globals?

I am more concerned about servers using specially customized config files. If they update the mod then they lose their settings. I may, however, consider replacing the entire config system in a future version.

**Comment by raymoo** [comment]
If you keep the same names and just drop them in the global table, migrating the config files would be straightforward for server operators. You could also maintain backwards-compatibility by checking if the globals exist, though that opens up hypothetical problems if other mods create those globals with different meanings before. A complicated solution would be to check their existence before and after running the config file, though it could be done without too much pain with a table of global names.

But if you do decide to replace the config system, this wouldn't be necessary, I agree.

**Comment by stujones11** [comment]
> that opens up hypothetical problems if other mods create those globals

If other mods create globals with conflicting names then it is their fault since this mod existed first.

**Comment by raymoo** [comment]
I don't think it's reasonable for every modder to look through all existing mods to see what globals they use. By convention, no mod has any claim to a global other than one of their name, anyway.

**Comment by stujones11** [comment]
> no mod has any claim to a global other than one of their name

If future mods do follow this convention then only the mod name could possibly conflict. It think it is highly unlikely someone would choose an all-caps name prefixed with ARMOR_

At the time I wrote this mod globals configs like this were quite common. In fact, I borrowed this idea from blockmen's hud mod iirc. I realize the fashion these days is to avoid using globals at all costs and if I was writing this now then I would do things differently, unfortunately It is difficult to change after the fact without upsetting someone.

**Comment by raymoo** [comment]
I'm sorry that I didn't appreciate the historical reasons for the use of globals like this. I don't think it would be difficult to account for config file usages of the globals in the way I mentioned earlier, but the change would still break mods that depend on the variables being global.

**Comment by stujones11** [comment]
Thanks, I will keep that in mind for the next release. As you rightly pointed out, I don't know of any other mods the relies on the presence of these globals.
