### ISSUE TITLE
Add a little info about how to use the mod

### ISSUE THREAD

**Issue by ensonic** [stujones11/minetest-3d_armor#69]
I just installed the mod and I can see the items in the inventory, but can't figure how to put them on. I've placed an armor stand and put items on it and that part works.

The README says "Recommends: inventory_plus or unified_inventory (use only one)", but I wonder it this is perhaps a hard requirement to have any of those.

**Comment by stujones11** [comment]
If you are not using an inventory mod then the armor slots should be visible in you main inventory window just to the left of the crafting grid. It is recommended, however, that you do use one of inventory mods for better overall compatibility.

**Comment by ensonic** [comment]
Thanks, I can indeed see them in the normal inventory, but not next to the crafting grid:
![screenshot from 2016-08-08 23 07 30](https://cloud.githubusercontent.com/assets/1279486/17496333/155e0106-5dbd-11e6-9239-cdbb4c22fd85.png)

What I can#t figure is how to put them on. When I press F7 to see my player character, I can't see the armor.

**Comment by stujones11** [comment]
I am not sure why the armor slots are not showing, perhaps a conflicting mod or something has changed in minetest game. I will look into this asap but for now I suggest you install one of the inventory mods and that should allow you to equip your armor in the meantime.

**Comment by ensonic** [comment]
Ohh yes, I had creative mode enabled. My kids liked the purely decorative aspect of having armor. I'll file a bug against minetest_game, since also in creative mode one can have damage.

**Comment by stujones11** [comment]
This is not a minetest or minetest_game bug, it is simply a shortcoming of this mod since it was never intended to be used as part of a creative game. You can use it in creative mode but you will need to install one of the suggested inventory mods. My apologies for not making this clear in the documentation.

**Comment by ensonic** [comment]
The code in question seems to be
https://github.com/stujones11/minetest-3d_armor/blob/master/3d_armor/armor.lua#L70-L108
Would it be possible to make this work with the normal inventory (from creative_mod)? Or is there lack of features there? I am not keen on installing a different inventory.

**Comment by ensonic** [comment]
I go with the minetest-technic/unified_inventory for now, but it seem all that is missing is a way to add custom formspecs to the creative inventory, right?

**Comment by stujones11** [comment]
8b8a554ff7ec66d4c4dfb577f05734ae653a4135
