### ISSUE TITLE
New 32bits textures

### ISSUE THREAD

**Issue by BrunoMine** [stujones11/minetest-3d_armor#70]
I'm working on 32-bit detailed textures (that's a comparison of resolution with the resolution of the nodes).
I want to keep my sync server with this repository, so a new branch can be interesting.
Textures are under license CC BY-SA 3.0.
Please create a new branch to pull the new textures.
[textures-32bits](https://github.com/BrunoMine/minetest-3d_armor/tree/textures-32bits)
![amostra armaduras](https://cloud.githubusercontent.com/assets/7986261/17757536/e27101c8-64bd-11e6-974d-c51f0eb105e1.jpg)

**Comment by stujones11** [comment]
The easiest way to avoid changing the mod itself is to add your 32px textures via a texture pack, iirc you can just drop the images into your minetest textures dir and they should automatically override those supplied by the mod. See: https://forum.minetest.net/viewtopic.php?f=4&t=1592 for full details.

**Comment by BrunoMine** [comment]
This mod is much more interesting if used on servers (and this is my case). textures packages do not work on servers.
I would like to share these textures on the mod itself. We can provide the textures in separate branchs.

**Comment by stujones11** [comment]
> textures packages do not work on servers.

Okay, that would be a problem I guess though I am keen on the idea of having to maintain multiple branches, at least not until version 0.5.0 released. I will give this some consideration.

**Comment by BrunoMine** [comment]
I believe you should not worry about it. I know you should worry about more important things than 32bit textures.
I think may be interesting only mensionar my idea (README?). Maybe someone is interested.

**Comment by stujones11** [comment]
Thank you, though I do like your textures and will try to think of a low maintenance way of making them available. Another branch is not altogether out of the question once I get down to only one ;-)

**Comment by stujones11** [comment]
I have since learned that it is indeed possible for servers to use custom texture packs and make them available to the client. I am sorry I do not know exactly how but since it is indeed possible I will now close this issue.
