### ISSUE TITLE
Repositioning pre preview

### ISSUE THREAD

**Issue by BrunoMine** [stujones11/minetest-3d_armor#71]
The aesthetics will be much more enjoyable if:
- Increase the size of the shield image.
- Place next to the chest.

![amostra escudo](https://cloud.githubusercontent.com/assets/7986261/17758268/4d6283c0-64c4-11e6-9d07-a179fad208bc.jpg)

If this idea was accepted, I commit myself to make adjustments.

**Comment by stujones11** [comment]
Looks good, however, preview images have been removed from the current development version. You may submit a PR if you wish so long as you are aware that it will not be included in the next version of the 3d_armor mod.

**Comment by BrunoMine** [comment]
Sorry, but I'm coming now in this project.
I believe this improvement is not necessary at this time.
