### ISSUE TITLE
u_skinsdb no longer works

### ISSUE THREAD

**Issue by eidy** [stujones11/minetest-3d_armor#73]
Always uses the original character skin when clothing mod is enabled instead of the one selected.
![screenshot_20160907_104228](https://cloud.githubusercontent.com/assets/12435947/18295812/dcaa395a-74e7-11e6-9953-dcee54de3d49.png)
![screenshot_20160907_104238](https://cloud.githubusercontent.com/assets/12435947/18295813/dcad2e12-74e7-11e6-9870-6c7a76850e4f.png)

**Comment by stujones11** [comment]
I have just pushed a commit to the development branch that should fix this 3d3dcb7d0765348dc09a73261e815be7dd0151cf
