### ISSUE TITLE
Licenses

### ISSUE THREAD

**Issue by SnarkBoojum** [stujones11/minetest-3d_armor#75]
Hi,

License.md is a bit evasive on which file falls under which license. There are several README.txt in the subdirs which also give different indications on who made what (numZero, HybridDog, poet.nohit, Cisoun, Ryan Jones, Stuart Jones).

I would like to package 3d_armor for Debian, but I need to settle these questions properly before it can be shipped.

Thanks!

**Comment by stujones11** [comment]
All textures, where not otherwise specified are WTFPL, however numZero is a typo (should be numberZero) and the reference to Cisoun is out-dated as no default textures are being used. I will update these documents as soon as soon as possible.

**Comment by stujones11** [comment]
Hopefully 4b70580ce42efde68220a34cdc0ac772c5d7fde9 straightens things out for you. Please let me know if I missed anything.

**Comment by SnarkBoojum** [comment]
It looks good, thanks!

**Comment by SnarkBoojum** [comment]
(though it could have years in for the WTFPL-licensed files)

**Comment by SnarkBoojum** [comment]
Perhaps I'll need a new release with the change or the Debian FTP Masters will reject the package: if the source says something and my copyright statements say something else, they might find it bad.

Could you arrange that?

**Comment by stujones11** [comment]
I can bump the version for you any time, however, if you do require dates for those WTFPL Licenses it may be the weekend before I get time to look back through the commit history.

**Comment by stujones11** [comment]
Okay, I did it anyway as they were not difficult to trace. I hope this now meets all the requirements.

**Comment by SnarkBoojum** [comment]
Perfect -- you just forgot to tag the new release :-P

Thanks!

**Comment by stujones11** [comment]
> you just forgot to tag the new release

I don't usually tag the current version, it's been kind of a rolling release where the current version is always master. I admit that is a little sloppy so I will add current release tag.

**Comment by SnarkBoojum** [comment]
I would prefer tagged releases, so I'm sure to package a stable version. Also the Debian tools will detect and notify me about new upstream versions if you tag them, so I'll be able to update the package more quickly.

**Comment by stujones11** [comment]
> I would prefer tagged releases

No problem, from now I will use a stable release system starting with version 0.4.7 as current-stable.

**Comment by SnarkBoojum** [comment]
Excellent, thanks!
