### ISSUE TITLE
new armorstand mapping

### ISSUE THREAD

**Issue by tobyplowy** [stujones11/minetest-3d_armor#76]
the mapping is perfect now it just needs a texture (if you wanna use it that is)
[armor stand model.zip](https://github.com/stujones11/minetest-3d_armor/files/722044/armor.stand.model.zip)

**Comment by tobyplowy** [comment]
@stujones11 i wanna make a pull but i dount have permission

**Comment by MT-Modder** [comment]
You have to fork the repo first then make changes to your fork. Then you should be able to make one.

**Comment by tobyplowy** [comment]
@MT-Modder is this good? https://github.com/stujones11/minetest-3d_armor/pull/77

**Comment by MT-Modder** [comment]
Perfect 👍

Github gave me a huge headache the first time I used it.

**Comment by tobyplowy** [comment]
@MT-Modder thx I'm happy that it works (github is so hard to learn) also I made a fast texture for it

**Comment by stujones11** [comment]
Thank you for sharing this, although I was not aware of any problems with the mapping, could you please explain?

**Comment by tobyplowy** [comment]
@stujones11 well now the model has its own texture it also has a nice mapping (every face on the model has a uneqe texture on the mapping) and also the mapping is more oginised (this it very usefull for texturepack makers)

**Comment by tobyplowy** [comment]
@stujones11 if you wanna help texturepack makers (I'm a texturepack maker bdw) than this is a must

**Comment by stujones11** [comment]
I had noticed it didn't look so good with certain TP's depending on the direction of the wood-grain so I guess supplying a specialized texture makes sense. Can you possibly post a screenshot of what it actually looks like in-game?

**Comment by tobyplowy** [comment]
@stujones11 left is the old model and riht is the new model
![naamffffloos](https://cloud.githubusercontent.com/assets/16853304/22184548/2bc4cd36-e0d4-11e6-9495-facd1822a065.png)

**Comment by tobyplowy** [comment]
i made a fast texture in the style of summefealds to show what can be done
![naamffffloos - kopie](https://cloud.githubusercontent.com/assets/16853304/22184660/b305b362-e0d6-11e6-9ad2-3f9f65613787.png)
this is what it shuld look like
![naddddddddddddddddamloos](https://cloud.githubusercontent.com/assets/16853304/22184665/d95691e4-e0d6-11e6-89b3-7a10bf3e60d2.png)

**Comment by stujones11** [comment]
I do like the look of the HD version, however, I think that the standard one still needs some work. I realize it is difficult to make nice looking wood with only 2 pixels and that's why 'I cheated' with the original model though I know that purists won't like that. Perhaps we can get some ideas from fences.

**Comment by tobyplowy** [comment]
@stujones11 Shuld I make a higher res texture to work with my mapping

**Comment by tobyplowy** [comment]
@stujones11

> though I know that purists won't like that

Yes that's why I made this model in the first place XD

**Comment by stujones11** [comment]
I think that the texture should be in-keeping with the default texture pack so I would prefer to keep it at the current resolution. People can add HD versions via TP if they want that,

**Comment by tobyplowy** [comment]
@stujones11 I'm really confused are you going to use my custom mapping or not :/

**Comment by tobyplowy** [comment]
@stujones11 also more detail in the wood 
![hd](https://cloud.githubusercontent.com/assets/16853304/22184925/edb2650a-e0db-11e6-8685-c295b98ab2a3.png)

**Comment by tobyplowy** [comment]
@stujones11 also with my mapping you can do this 
![hd](https://cloud.githubusercontent.com/assets/16853304/22184953/72ea8b08-e0dc-11e6-88ad-35fc669c6bc1.png)
i dunno why you wuld wanne do this but its possible XD

**Comment by stujones11** [comment]
> I'm really confused are you going to use my custom mapping or not :/

The mapping seems fine, I am just not sure about the default texture but I can sort that one.

**Comment by tobyplowy** [comment]
@stujones11 its very customisable so you can make it what you want

**Comment by numberZero** [comment]
@tobyplowy Sounds good, but need better default texture. Probably something like the “new” variant you suggested:
![](https://cloud.githubusercontent.com/assets/16853304/22184660/b305b362-e0d6-11e6-9ad2-3f9f65613787.png)
It is very nice, only the plate needs to be less detailed to fit the MT style.

**Comment by tobyplowy** [comment]
@numberZero  no that was to show off texture pack possibilities that's not a texture for the mod

But I can make something similar

**Comment by tobyplowy** [comment]
@numberZero is this texture good?
![cddddddd](https://cloud.githubusercontent.com/assets/16853304/22185749/6ed1713a-e0eb-11e6-9233-eee0756e349f.png)

![armor_stand](https://cloud.githubusercontent.com/assets/16853304/22185753/739149b6-e0eb-11e6-85a4-9b0f3d37ef3c.png)

**Comment by numberZero** [comment]
Reasonable. I suggest you to use higher resolution for the details (as [here](https://github.com/Jeija/minetest-mod-mesecons/blob/master/mesecons_luacontroller/textures/jeija_luacontroller_top.png): notice smaller “pixels” at port names)

**Comment by tobyplowy** [comment]
@numberZero Would You be interested in making a Texture?

**Comment by numberZero** [comment]
@tobyplowy oh well, maybe. I wish I had more time...

**Comment by tobyplowy** [comment]
@numberZero I will probably make it later then

**Comment by stujones11** [comment]
I have now merged your PR with some minor changes, however, full credit goes to you for your efforts.

![screenshot_20170125_193136](https://cloud.githubusercontent.com/assets/3710749/22306927/105c0458-e339-11e6-80c3-f653e32ae0ed.png)
I will let you close this issue if you are happy with this.

**Comment by tobyplowy** [comment]
@stujones11 no problem I should thank you and all the other people helping with this mod and minetest in general so thanks I mean it!
