### ISSUE TITLE
Armor tab in creative

### ISSUE THREAD

**Issue by tobyplowy** [stujones11/minetest-3d_armor#78]
You may not see why this is useful but this is really useful for testing purposes also why is it not there :/

**Comment by stujones11** [comment]
You can simply install one of the supported inventory mods. Related #69

I do, however, plan to add support for sfinv as soon as I get a chance, I will look at making armor available in creative mode then.

**Comment by rubenwardy** [comment]
#82

**Comment by ForbiddenJ** [comment]
My mod I mentioned over at https://github.com/stujones11/minetest-3d_armor/issues/86 will do that. It overrides the crafting page, however I'd like to see if it's original functionality can be merged into this mod once sfinv is fixed. :)

**Comment by stujones11** [comment]
8b8a554ff7ec66d4c4dfb577f05734ae653a4135
