### ISSUE TITLE
Possible to place nodes into top half of armor stand

### ISSUE THREAD

**Issue by Wuzzy2** [stujones11/minetest-3d_armor#79]
![](https://github.com/zaoqi/files/raw/master/%E6%B7%B1%E5%BA%A6%E6%88%AA%E5%9B%BE20170205150932.png)

You can place nodes on top of an armor stand. Just look at the top of the armor stand and shift+rightclick with a node in hand to place it. The node will oddly end up *inside* the top half of the armor stand.

**Comment by numberZero** [comment]
MTG doors use an invisible non-buildable-to node to prevent that.

**Comment by stujones11** [comment]
I would have a tendency to say "then just don't do that" but I guess it should be fixed. Thank you for reporting this.

**Comment by stujones11** [comment]
c691f3e21918183984c401d647f3d3178cb2b2d0 should now prevent this though it does not stop you placing an armor stand beneath another node, that has always been possible and I don't see any harm in it, I just want to keep this simple. I am not willing to go to all the lengths doors do to avoid this sort of thing, if people want to make their worlds look ridiculous then that is up to them.

**Comment by BrunoMine** [comment]
Trying to keep something as realistic as possible is to avoid glitch.

**Comment by stujones11** [comment]
> Trying to keep something as realistic as possible is to avoid glitch.

I doesn't really cause any glitch other than visual and only if people deliberately place them somewhere stupid. In fact I could even claim it is a feature as it can look quite effective with the right nodes.

Building over the top of the stand was definitely a bug, however, that should now be fixed. If anyone is genuinely unhappy about the placing under nodes thing then please open a new issue.

**Comment by numberZero** [comment]
Doesn’t it? What if the block right above the armor stand is protected by someone else?

Also what if that `ignore` is unloaded area, won’t it be able to replace something wrong? (I don’t know how exactly that engine part works)

**Comment by stujones11** [comment]
> What if the block right above the armor stand is protected by someone else?

The mesh only takes up the position you place it in, protection is handled for that place by whichever protection mod is in use. You may be right about `ignore` though, I will change that and add a protection check for the hidden nodes. This will not stop the item visually protruding into the protected area but I think the chances of armor stand grief are quite slim.

**Comment by BrunoMine** [comment]
> protection is handled for that place by whichever protection mod is in use
Protection mods do not see the length of the nodes. 
The placement of other coordinates must be performed by the mod that registers the node.
