### ISSUE TITLE
Armor is Lost Permanently When Bones Can't Be Placed Due to Protection

### ISSUE THREAD

**Issue by expertmm** [stujones11/minetest-3d_armor#84]
Hello, this issue is repeatable at least when using TenPlus1's protector redo.
Upon death, armor is successfully placed in bone block, except when bone block is dropped (floating) instead of placed--this occurs when the area is protected and the bone block is not allowed to be placed. In this case, the armor is gone permanently.

**Comment by stujones11** [comment]
Being unable to locate the bones node has long since been a problem, however, it should fall-back to dropping the armor as items in this situation. It seems #65 added a possible return path that skips the armor drop code.
