### ISSUE TITLE
Cactus Armor armor_use

### ISSUE THREAD

**Issue by johnnyjoy** [stujones11/minetest-3d_armor#89]
It seems that all armor of a single type has the exact same armor_use, except for 3d_armor:boots_cactus. All other cactus items have a armor_use of 1000, but the boots have 2000, which is the same as all wood armor items above. Not sure if this is a cut&paste error or as intended. 

https://github.com/stujones11/minetest-3d_armor/blob/master/3d_armor/init.lua#L54

**Comment by stujones11** [comment]
I did not add the cactus armor myself so I can't answer that, however, making it 1000 would be consistent with other armor so I suspect your are probably correct.
