### ISSUE TITLE
Cannot walk

### ISSUE THREAD

**Issue by mase76** [stujones11/minetest-3d_armor#96]
Hi!
Since one of the last git changes, my players are unable to walk. Legs and arms are moving,
but they don't change their positions. Also jumping is not possible.
Must be one of the commits shortly before March 27th 2017.

**Comment by stujones11** [comment]
Please see my reply to #97

**Comment by mase76** [comment]
Ah ok!

**Comment by stujones11** [comment]
3aac5c98f4a95fac9136af63ab129ca4bb1246cf
