### ISSUE TITLE
Cannot move without "crystal boots"

### ISSUE THREAD

**Issue by bell07** [stujones11/minetest-3d_armor#97]
Something is wrong with physics now. If armor mod is enabled is not possible to move. Gravity and max-speed seems to be zero now. "Crystal boots" helps to move, but if you jump you cannot come down. Tested with minetest_game + armor-modpack.

**Comment by stujones11** [comment]
Thanks, the problem has been reported on the forums. It's any easy fix but I only have mobile access atm and it's difficult enough for me to reply let alone edit code :(

See line comments on 11ce84873bcef15e20764e808fd3a97757d913ea

**Comment by bell07** [comment]
Thanks! The proposed change in line 160 did solved the issue for me

**Comment by stujones11** [comment]
3aac5c98f4a95fac9136af63ab129ca4bb1246cf
