### ISSUE TITLE
armor.def[].level and armor.def[].groups not resetted on armor removal

### ISSUE THREAD

**Issue by bell07** [stujones11/minetest-3d_armor#98]
If I apply armor to the player, the fields armor.def[playername].level and armor.def[playername].groups[] are filled. But If I remove again the armor (the last one, full undressed) the level field and groups table does contain still the last values.
Test environment: minestest_game + armor modpack + qa_block to look into armor.def[]

**Comment by stujones11** [comment]
Thanks, I will look into it asap.

**Comment by stujones11** [comment]
Should be fixed now 3aac5c98f4a95fac9136af63ab129ca4bb1246cf
